### ISSUE TITLE
Add direct access methods to Lists and depreciate Arrays

### ISSUE THREAD

**Issue by ericpauley** [ericpauley/Alice#2]
Arrays and lists could easily be merged. I hope to add the methods of arrays to the less buggy lists, and then remove the ability to create arrays. This would allow worlds made with normal alice using arrays to still run.

**Comment by jediaction** [comment]
How do I create my own ideas. I mean, where do I post my "view/angle" changes that I told you about.

**Comment by ericpauley** [comment]
On the main issues screen click the new issue button.
